input {
    file {
        path => "/logs/*.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        codec => json
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "spring-logs-%{+YYYY.MM.dd}"
    }

    stdout {
        codec => rubydebug
    }
}